import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Music School",
	description: "Generated by WHOM?",
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className="dark">
			<body className={inter.className}>
				<div className="relative flex items-center justify-center w-full ">
					<Navbar />
				</div>
				{children}
			</body>
		</html>
	);
}
