import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import AuthSection from "@/Components/AuthSection";
// import { Provider } from "react-redux";
// import store from "@/store/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Music School",
	description: "Generated by WHOM?",
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className="dark">
			{/* <Provider store={store}> */}
				<body
					className={`${inter.className} relative min-h-screen bg-black/[0.96] antialiased bg-grid-white/[0.02] `}>
					<AuthSection />
					<Navbar />
					{children}
					<Footer />
					<div></div>
				</body>
			{/* </Provider> */}
		</html>
	);
}
