import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "./ClientProvider";
import ClientLayout from "./ClientLayout";

export const metadata: Metadata = {
	title: "Music School",
	description: "Generated by WHOM?",
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className="dark relative min-h-screen bg-orange/[0.76] antialiased bg-grid-white/[0.1]">
			<body>
				<ClientProvider>
					<ClientLayout>{children}</ClientLayout>
				</ClientProvider>
			</body>
		</html>
	);
}
